### ISSUE TITLE
Multi-config IPAM feature

### ISSUE THREAD

**Issue by sunya-ch** [foundation-model-stack/multi-nic-cni#155]
**Is your feature request related to a problem? Please describe.**

For L2 mode, there is no need to use host-interface block IP allocation. Instead, the existing single-NIC IPAM such as whereabouts provides more flexibility. 
However, the current design does not support defining multiple config (such as different subnet for different interface name) for single-NIC IPAM. 

**Describe the solution you'd like**

Multi-config IPAM is a feature to allow that in multinicnetwork IPAM definition.
I define a new IPAM type called `multi-config` which has struct as below:

```go
	Name     string
	Type     string                            `json:"type"`
	IpamType string                            `json:"ipam_type"`
	Args     map[string]map[string]interface{} `json:"args"`
	Routes   []*types.Route                    `json:"routes"`
```
 
The multinicnetwork IPAM should be defined like:
```yaml
apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
  name: multinic-ipvlanl2
spec:
  subnet: "172.31.49.0/24"
  ipam: |
    { 
      "type": "multi-config",
      "ipam_type": "whereabouts",
       "args": {
            "eth1": {
                  "range": "192.168.0.0/18"
             },
            "eth2": {
                  "range": "192.168.64.0/18"
             }
        }
    }
  multiNICIPAM: false
  plugin:
    cniVersion: "0.3.0"
    type: ipvlan
    args: 
      mode: l2
```

_note:_ 
_As with L2 on some system, there is no IP address assigned to the host interface. So that, we use master name instead of the network address._

**Describe alternatives you've considered**

**Additional context**
