### ISSUE TITLE
Set static IPs for a specific pod

### ISSUE THREAD

**Issue by sunya-ch** [foundation-model-stack/multi-nic-cni#156]
**Is your feature request related to a problem? Please describe.**

In some case, users want to set static IP on a specific pod such as API server, storage. 

**Describe the solution you'd like**

When the `IP(ips)` is annotated at `k8s.v1.cni.cncf.io/networks`, it should set the static IP address in the same order defined in `cni-args`.

```yaml
        "cni-args": {
          "masters": ["eth1", "eth2"]
        },
        "ips": [ "192.168.0.1/18", "192.168.64.1/18" ]
```

_note: this should be applicable only for single-NIC IPAM with `masters` annotations to ensure the order_

**Describe alternatives you've considered**

**Additional context**
