### ISSUE TITLE
revisit sriov support

### ISSUE THREAD

**Issue by sunya-ch** [foundation-model-stack/multi-nic-cni#213]
```yaml
spec:
  subnet: "172.34.0.0/16"
  ipam: |
    {
      "type": "multi-nic-ipam",
      "hostBlock": 8,
      "interfaceBlock": 2,
      "vlanMode": "l2"
    }
  multiNICIPAM: true
  plugin:
    cniVersion: "0.3.0"
    type: sriov
    args:
      numVfs: "2"
      isRdma: "true"
```
[Sample MultiNicNetwork](https://github.com/foundation-model-stack/multi-nic-cni/blob/main/config/samples/multinicnetwork/sriov.yaml)

### How it works?

Requires sriov-operator to operate configuration

#### Controller automatically generate NetworkAttachmentDefinition (NAD)

The important function is [GetConfig](https://github.com/foundation-model-stack/multi-nic-cni/blob/aa1e9d4416758844b1ef9f787883217d3305bd0a/internal/plugin/sriov.go#L65) function

It does the following steps:
- 1. create a new SriovNetworkPolicy (new resource name generated from MultiNicNetwork name) if the `resourceName` is not defined in `args`. 
      - The policy is created from the provided args including priority, mtu, numVfs, isRdma, needVhostNet
      - The policy will automatically add the rootDevices field from the network address defined in spec.masterNets if exists
- 2. create `SriovNetwork` --> this SriovNetwork will be operated by sriov operator and generate a different NAD
- 3. render NAD from the sriovnet and add resource name from the step in annotations. 

The key is step 1 and step 3.

Note that, step 2 might not require the creation to the API server. Need to check whether sriov operator does anything else more than just creating a NAD. 

The functionalities of Muti-NIC CNI for SR-IoV use case is that, 
1. Auto generate sriovnetwork policy and corresponding NAD by list of network addresses (single point of definition)
2. Apply Multi-NIC IPAM to compute host-interface range CIDR which allow applying L3 policy on each interface

---

### Tasks
- Try sample SR-IOV MultiNicNetwork
- Check compatibility to SR-IOV operator
- Update controller or CNI as needed
- Add sample use case with predefined resource name and test
- Revisit this folder: https://github.com/foundation-model-stack/multi-nic-cni/tree/main/config/samples/sv-iov
