### ISSUE TITLE
Fill the gap between v1.3.0 and alpha v1.2.x

### ISSUE THREAD

**Issue by sunya-ch** [foundation-model-stack/multi-nic-cni#256]
There are a significant improvement introduced to version 1.3.0. However, there is not enough track to forward the bug fixes and update since v1.2.3 to v1.3.0.

```
v1.3.0 (based on v1.2.2)

Improvements:

- Make all fields except interfaceName in HostInterface.Interfaces optional
- Add namespace watcher to add NetworkAttachmentDefinition when new namespace is created
- Set manager container as default container in controller
```

We need to rebase v1.3.0 or reimplement the feature introduced from v1.3.0 based on the latest v1.2.x.

**Comment by sunya-ch** [comment]
```mermaid
flowchart LR;
v1.2.0--beta-->v1.2.3
v1.2.3--stable1.2-->v1.2.4
v1.2.4--alpha1.2-->v1.2.5
v1.2.5-->v1.2.6
v1.2.6-->v1.2.7
v1.2.0--alpha-->v1.2.1
v1.2.1-->v1.2.2
v1.2.2-->v1.3.0

```

To-dropped features were added in v1.2.1 including:

- Unmanaged HostNetworkInterface for IP-less network device

  - zero host block/zero interface block
```yaml
apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
    name: multinic-unmanaged
spec:
    ipam: |
        {
        "type": "multi-nic-ipam",
        "hostBlock": 0, 
        "interfaceBlock": 0,
        "vlanMode": "l2"
        }
    multiNICIPAM: true
    plugin:
        cniVersion: "0.3.0"
        type: ipvlan
        args: 
            mode: l2
```
  - specify static cidr of each host

```yaml
apiVersion: multinic.fms.io/v1
kind: HostInterface
metadata:
    name: node-1
    labels:
      multi-nic-unmanaged: "true"
spec:
    hostName: node-1
    interfaces:
    -   hostIP: ""
        interfaceName: eth1
        netAddress: 192.168.0.0/24
        pciAddress: ""
        product: ""
        vendor: ""
    -   hostIP: ""
        interfaceName: eth2
        netAddress: 192.168.1.0/24
        pciAddress: ""
        product: ""
        vendor: ""
```
- Multi-gateway route configuration support

```yaml
apiVersion: multinic.fms.io/v1
kind: MultiNicNetwork
metadata:
    name: multinic-multi-gateway
spec:
    ipam: |
        {
        "type": "multi-nic-ipam",
        ...
        "routes": [{"dst": "10.0.0.0/24","gw": "1.1.1.1"}, {"dst": "10.0.0.0/24","gw": "2.2.2.2"}]
        }
    multiNICIPAM: true
````

The above definition will generate the following route on pod:

10.0.0.0/24 nexthop via 1.1.1.1 nexthop via 2.2.2.2
