### ISSUE TITLE
Add corresponding IPPool to CIDR spec

### ISSUE THREAD

**Issue by sunya-ch** [foundation-model-stack/multi-nic-cni#48]
**Is your feature request related to a problem? Please describe.**

Currently, IPPool name is implied by the podCIDR and network name.
For explicitly associating IPPool name of specific host from the CIDR, we may add the `ippool` attribute in `spec.cidr.hosts`. 

**Describe the solution you'd like**

```yaml
spec:
   cidr:
    ...
    - hosts:
      - hostIP: 10.244.0.246
        hostIndex: 0
        hostName: kwok-node-1
        interfaceName: eth0
        ippool: multi-nic-sample-192.168.0.0-26
        podCIDR: 192.168.0.0/26
      - hostIP: 10.244.0.247
        hostIndex: 1
        hostName: kwok-node-2
        interfaceName: eth0
        ippool: multi-nic-sample-192.168.0.64-26
        podCIDR: 192.168.0.64/26
      interfaceIndex: 0
      netAddress: 10.244.0.0/16
      vlanCIDR: 192.168.0.0/18
...
```

**Describe alternatives you've considered**

**Additional context**

Signed-off-by: Sunyanan Choochotkaew <sunyanan.choochotkaew1@ibm.com>
